---

- hosts:
    - Hulk.local
    - captain.local
    - ironman.local
    - batman.local
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:

    - name: "Send the node_api python file"
      synchronize:
        src: "../node_api.py"
        dest: "/home/pi/pi_venv/"
...